# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master
pool: 
 name: default  #bhttps://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#software
 demands: 
 - Agent.Version -equals 2.200.2
steps:
- task: Maven@3
  displayName: ean clbuild and package the app
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'D:\soft\liberica-jdk-11'
    jdkVersionOption: '11'
    jdkUserInputPath: 'D:\soft\liberica-jdk-11'
    mavenVersionOption: 'Path'
    mavenDirectory: 'c:\soft\apache-maven'
    mavenSetM2Home: false
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
    goals: clean package
    

#- task: Maven@3
#  displayName: Build Docker image using buildpack
#  inputs:
#      mavenPomFile: 'pom.xml'
#      goals: 'spring-boot:build-image'
#      publishJUnitResults: false
#      javaHomeOption: 'D:\soft\liberica-jdk-11'
#      jdkVersionOption: '11'
#      jdkUserInputPath: 'D:\soft\liberica-jdk-11'
#      mavenVersionOption: 'Path'
#      mavenDirectory: 'c:\soft\apache-maven'
#      mavenSetM2Home: false
#      mavenAuthenticateFeed: false
#      effectivePomSkip: false
#      sonarQubeRunAnalysis: false
